services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    depends_on:
      - postgres
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data

  backend:
    build: ./backend-api
    ports:
      - "3001:3001"
    environment:
      KEYCLOAK_URL: http://keycloak:8080/auth
      KEYCLOAK_REALM: your-realm
      KEYCLOAK_CLIENT_ID: backend-api
      KEYCLOAK_CLIENT_SECRET: your-client-secret
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend
      POSTGRES_HOST: postgres
    depends_on:
      - keycloak
      - postgres
    volumes:
      - ./backend-api/data:/app/data

  frontend:
    build: ./frontend-app
    ports:
      - "3000:3000"
    environment:
      REACT_APP_KEYCLOAK_URL: http://keycloak:8080/auth
      REACT_APP_KEYCLOAK_REALM: your-realm
      REACT_APP_KEYCLOAK_CLIENT_ID: frontend-app
    depends_on:
      - keycloak

  volumes:
    postgres_data:
    keycloak_data: